Task-01-1
jurgita-vcs/Coherent-HomeTasks pull request #1
Opened 2021-12-01 12:25 UTC by jurgita-vcs

PR of first homework, Task-01.

2021-12-03 11:14 UTC, rkireevLT requested changes

2021-12-03 11:14 UTC, rkireevLT commented on CoherentSolutionsTasks/Program.cs
> +            Console.WriteLine("Coherent Solutions Tasks");
That file and folder (CoherentSolutionTasks\Program.cs) are not required, remove.

2021-12-03 11:14 UTC, rkireevLT commented on Task01-1/Program.cs
> +                PrintTernaryNumber(a, b);
The goal was to locate numbers what have 2 twos in ternary representation. 
For example:
User enters a = 0 and b = 10.
The app converts numbers in range 0-10 to ternary
0 => 000
1 => 001
2 => 002
3 => 010
4 => 011
5 => 012
6 => 020  
7 => 021
8 => 022      // this one has two "2"s.
9 => 100
10 => 101 

The output should be "8"

2021-12-03 11:14 UTC, rkireevLT commented on Task01-1/Program.cs
> +                    return (false);
do not need in parenthesis

2021-12-03 11:14 UTC, rkireevLT commented on Task01-1/Program.cs
> +                    return (true);
do not need in parenthesis

2021-12-03 11:14 UTC, rkireevLT commented on Task01-1/Program.cs
> +                if ((num != 0) && (num != 1) && (num != 2))
do not need in parenthesis around num != 0 and other comparisons

2021-12-03 13:07 UTC, jurgita-vcs commented on Task01-1/Program.cs
> +                    return (false);
Yes, I know. But I used to use. It's really more readable code https://social.technet.microsoft.com/wiki/contents/articles/37763.c-if-else-statement-curly-braces-or-not-an-in-depth-analysis.aspx
"Well if there is only one statement to execute after if condition then using curly braces or not doesn't make it different. Without curly braces only first statement consider in scope so statement after if condition will get executed even if there is no curly braces. But it is Highly Recommended to use curly braces. Because if the user (or someone else) ever expands the statement it will be required."

2021-12-09 10:50 UTC, radislavkireev commented on Task01-1/Program.cs
> +                    return (false);
I mean not curly braces, but 
(false) is replacable with false;

2021-12-09 11:08 UTC, radislavkireev requested changes

2021-12-09 11:08 UTC, radislavkireev commented on Task01-1/Program.cs
> +            for (var i = a; i <= b; i++)
There were no requirement to print ternary numbers. 
Appears that the code converts numbers from [a..b] to ternary three times:
PrintConvertedTernaryNumbers converts once, PrintTwoOfTwos converts 2 times more. 

Drop the method PrintConvertedTernaryNumbers

2021-12-09 11:08 UTC, radislavkireev commented on Task01-1/Program.cs
> +            return CountOccurrenceOfTwo(number) == 2 ? number : 0;
This method is not needed, drop it

2021-12-09 11:08 UTC, radislavkireev commented on Task01-1/Program.cs
> +                var number1 = ConvertNumberToTernary(i);
There is no need to call  ConvertNumberToTernary twice for each number. 

the method should be reduced to 
```
 for (var i = a; i <= b; i++)
 {
     if(CountOccurrenceOfTwo(ConvertNumberToTernary(i)) == 2)
     {
         Console.WriteLine(i);
     }
}
```

2021-12-13 14:11 UTC, jurgita-vcs commented on Task01-1/Program.cs
> +                    return (false);
Sorry, misunderstood.

2021-12-14 10:32 UTC, radislavkireev commented on Task01-1/Program.cs
> +                if (remainder == 2)
add {}

2021-12-14 10:32 UTC, radislavkireev approved these changes

2021-12-14 14:27 UTC, merged